### ISSUE TITLE
Implement check result package

### ISSUE THREAD

**Issue by lazyfrosch** [NETWAYS/go-check#1]
Enhance `result.overall` to allow deeper hierarchy and better structure.

Maybe build a check result, and combinable package.

See also
* https://github.com/Icinga/icinga-powershell-framework/blob/master/doc/developerguide/01-New-IcingaCheck.md
* https://github.com/Icinga/icinga-powershell-framework/blob/master/doc/developerguide/02-New-IcingaCheckPackage.md

**Comment by RincewindsHat** [comment]
Started something in https://github.com/NETWAYS/go-check/tree/Introduce_subchecks

**Comment by RincewindsHat** [comment]
Is implemented, closing this.
