### ISSUE TITLE
Output breaks a little bit, if percent signs are used (SPrintf)

### ISSUE THREAD

**Issue by RincewindsHat** [NETWAYS/go-check#31]
Scenario:
```go
package main

import (
	"github.com/NETWAYS/go-check"
	"github.com/NETWAYS/go-check/result"
)

func main() {
	var overall result.Overall

	overall.AddOK("Test%")

	check.Exit(overall.GetStatus(), overall.GetOutput())
}
```
Expected Result: 
```
OK - states: ok=1
[OK] Test%
```
Actual Result:
```
OK - states: ok=1
[OK] Test%!
(MISSING)
```

Reason: Dunno

**Comment by RincewindsHat** [comment]
ok, the reason is line 21 in `exit.go`, it puts the output in Sprintf. I find this rather unfortunate to be honest. wouldn't it be clearer, if you had to format the strings yourself and the `Exit()` function would only collect them?

**Comment by lazyfrosch** [comment]
I guess the main problem is that we never introduced a simple exit function without formatting, so `Exit()` should have been plain, and `ExitF()` with formatting.

I'll introduce two new functions for that, deprecating `Exit()`
