### ISSUE TITLE
Misleading name of metric

### ISSUE THREAD

**Issue by pdorschner** [NETWAYS/go-check#45]
Due to the fact, that #44 only supports IEC units and not all Uoms, the name of the package is not correct and misleading.

My recommendation for the "new" package name would be `IECmetrics`. 

Any other opinions?

**Comment by RincewindsHat** [comment]
It depends: If you want to cover a broader spectrum of different measurement units, I would totally go for `metrics` (or maybe `units` or something like that and not even make a distinction between *IEC* and *SI* (or create subpackages for that).
If you want to focus solely on *Bytes*, if might be more intuitive to use something like `metrics/bytes` or `units/bytes`.

In any case, it might be worth thinking about how this relates to the `convert` part of this library.

**Comment by RincewindsHat** [comment]
See #91

**Comment by martialblog** [comment]
Fixed by removing the code for now #91
