### ISSUE TITLE
Evaluate the allowed characters for perfdata label

### ISSUE THREAD

**Issue by RincewindsHat** [NETWAYS/go-check#48]
At least the combination Icinga 2 + InfluxDB + Grafana seems to handle Unicode characters well, so maybe we should allow those.
Someone has to test that for Graphite and RRD backends.

**Comment by martialblog** [comment]
@RincewindsHat and I think we can loosen the regex a bit and only remove the most critical characters (quotes)

**Comment by martialblog** [comment]
@RincewindsHat This should also be in v0.5.0
