### ISSUE TITLE
PartialResults: Move perfdata to the end of the output

### ISSUE THREAD

**Issue by RincewindsHat** [NETWAYS/go-check#62]
To achieve better compatibility with Naemon and similar systems, perfdata should be move uncondtitionaly to the end of the output.
They might not support having them at the end of each line.

**Comment by martialblog** [comment]
Isn't that already the case? 

```
OK - Server is Healthy. | statuscode=200
```

Or do you mean this?

```
CRITICAL - Access Denied! | statuscode=401
exit status 2
```

**Comment by martialblog** [comment]
Isn't that something the user can decide? It all depends on how I create my CheckPlugin's output. Or am I missing something?

If you use the `perfdata.PerfdataList Add()` and then the `String()` func everything is rendered as expected.  Example from the `check_logstash`:

` ./check_logstash pipeline 
CRITICAL - Inflight events not alright
 \_[CRITICAL] inflight_events_main:123;
 \_[CRITICAL] inflight_events_two:123; | pipelines.main.events.in=123c pipelines.main.events.out=123c inflight_events_main=123;500;1000 pipelines.main.reloads.failures=0 pipelines.main.reloads.successes=0 pipelines.two.events.in=123 pipelines.two.events.out=78443731c inflight_events_two=-123;500;1000 pipelines.two.reloads.failures=0 pipelines.two.reloads.successes=0
`

**Comment by RincewindsHat** [comment]
but not yet, if you add perfdata to partial results (see example `TestOverall_withEnhancedSubchecks` in `result/overall_test.go` )

**Comment by martialblog** [comment]
I see. I updated the headline accordingly

**Comment by RincewindsHat** [comment]
@martialblog Put some changes in there. What do you think about it?
