### ISSUE TITLE
Idea: Remove go-ps dependency

### ISSUE THREAD

**Issue by martialblog** [NETWAYS/go-check#94]
Right now we are importing `go-ps` for just one reason, finding out if we run in the delve debugger.

```
	if parent, err := ps.FindProcess(ppid); err == nil {
		if parent.Executable() == "dlv" {
```

I do like to minimize dependencies as much as possible. Do we want to remove that piece of code or comment it out?

If I really really need to run delve, I can still enable it for debugging only. No need to ask the users to import it as a dependency

**Comment by martialblog** [comment]
@pdorschner @RincewindsHat What do you think?

**Comment by pdorschner** [comment]
I completely agree. It's only needed for a single case, and importing an entire package for that purpose doesn't make sense.
