### ISSUE TITLE
Proposal: Provide constants for check status strings

### ISSUE THREAD

**Issue by martialblog** [NETWAYS/go-check#99]
Currently we have the four possible states as constants in status.go for use in downstream code

```
const (
	OK = 0
	Warning = 1
	Critical = 2
	Unknown = 3
)
```

We should maybe provide the same for the corresponding status texts. We got a function for that. But I think that's way too verbose in downstream code:

To get the string "OK" `check.StatusText(check.OK)`

Proposal:

```
const (
	OKString = "OK"
	WarningString  = "WARNING"
	CriticalString  = "CRITICAL"
	UnknownString  = "UNKNOWN"
)
```

Suggestions for names are welcome...

**Comment by RincewindsHat** [comment]
If golang would provide a way to declare const maps or arrays, this could be nicer.
But yeah, constants can't hurt in general. Not sure if we want to remove the function yet, though.
Names are fitting, no objections.
